project_id = "nexerp-development"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:4173"
additional_redirect_urls = ["http://localhost:4173", "https://erp.momoshop.mn"]
enable_signup = false

[realtime]
enabled = true
